Upgrade to groovy 2.3.9.
Reason : java.lang.NoClassDefFoundError: org/codehaus/groovy/runtime/typehandling/ShortTypeHandling
at com.predic8.util.HTTPUtil.updateBaseDir(HTTPUtil.groovy:31)

unit tests
before : Tests run: 372, Failures: 6, Errors: 347, Skipped: 0
after  : Tests run: 377, Failures: 5, Errors: 2, Skipped: 0